---
        -name: installing and launching metricbeat
         hosts: webservers
         become: yes
         tasks:



         - name: download metricbeat .deb
           command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-darwin-x86_64.tar.gz
tar xzvf metricbeat-7.6.1-darwin-x86_64.tar.gz
cd metricbeat-7.6.1-darwin-x86_64/
          

         - name: download metricbeat .deb
           command: dpkg -i metricbeat-7.4.0amd64.deb

         - name: drop in metricbeat.yml
           copy:
             src: /etc/metricbeat/metricbeat-config.yml
             dest: /etc/metricbeat/metricbeat.yml

         - name: enable and configure system module
           command: metricbeat modules enable docker

         - name: setup metricbeat
           command: metricbeat setup

         - name: start metricbeat
           command: metricbeat -e 

         - name: enable metricbeat on boot
           systemd:
             name: metricbeat
             enabled: yes

